const skillsList = [
  "Python",
  "Java",
  "JavaScript",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Swift",
  "Go",
  "Kotlin",
  "HTML/CSS",
  "React.js",
  "Angular",
  "Vue.js",
  "Node.js",
  "Django",
  "Ruby on Rails",
  "ASP.NET",
  "SQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Oracle Database",
  "iOS App Development (Swift, Objective-C)",
  "Android App Development (Java, Kotlin)",
  "React Native",
  "Flutter",
  "Amazon Web Services (AWS)",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "Cloud Security",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Continuous Integration/Continuous Deployment (CI/CD)",
  "Ethical Hacking",
  "Information Security",
  "Penetration Testing",
  "Cybersecurity Tools (e.g., Wireshark)",
  "Machine Learning",
  "Data Analysis",
  "Big Data",
  "Data Visualization (e.g., Tableau, Power BI)",
  "Agile",
  "Scrum",
  "Waterfall",
  "Kanban",
  "Git",
  "GitHub",
  "Bitbucket",
  "Linux",
  "Windows",
  "macOS",
  "TCP/IP",
  "Routing",
  "Switching",
  "Network Security",
  "Bash/Shell Scripting",
  "PowerShell",
  "Automation Tools (e.g., Ansible)",
  "IoT Development",
  "Embedded Systems",
  "Data Warehousing",
  "NoSQL Databases",
  "Data Modeling",
  "VMware",
  "VirtualBox",
  "Hyper-V",
  "RESTful APIs",
  "SOAP",
  "GraphQL",
  "Project Planning",
  "Agile Project Management",
  "Jira",
  "Manual Testing",
  "Automated Testing (e.g., Selenium)",
  "User Interface (UI) Design",
  "User Experience (UX) Design",
  "Prototyping",
  "Blockchain Development",
  "Smart Contracts",
  "TensorFlow",
  "PyTorch",
  "NLP Libraries (NLTK, spaCy)",
  "AWS Lambda",
  "Azure Functions",
  "Google Cloud Functions",
  "Microservices Architecture",
  "Docker Compose",
  "Deployment Automation",
  "Release Management",
];

export default skillsList;
